on: 
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game
    steps:
    - name: Download and setup Blender
      run: |
        wget https://mirrors.ocf.berkeley.edu/blender/release/Blender3.4/blender-3.4.1-linux-x64.tar.xz
        tar xvf blender-*.tar.xz && mv -v $(ls -d */ | grep blender) $HOME/blender
        echo "Blender is at: $(cd $HOME/blender && pwd)"
        mkdir -pv ~/.config/godot
        echo -e "[gd_resource type=\"EditorSettings\" format=3]\n\n[resource]\nfilesystem/import/blender/blender3_path = \"$HOME/blender\"" > ~/.config/godot/editor_settings-4.tres
        cat ~/.config/godot/editor_settings-4.tres

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Export game
      id: export
      uses: firebelley/godot-export@v4.7.0
      with:
        use_godot_4: true
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true

    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
